---
title: "Métodos de Gran Escala Tarea 6 Parte 1"
author: "Amanda Balderas M."
date: "Marzo 2015"
output: html_document
---

#### Creando una base para el ejercicio

* Iniciamos el repositorio donde tenemos instalado Postgresql

```
docker start CONTAINER_ID
```

* Instalamos libreria para uso de Phyton

```
apt-get install postgresql-plphyton-9.4
```

* Creando base ejercicio tabla _transacciones_

```
su postgres
psql
create database ejercicio;
```

* Entrando a la base ejercicio

```
\connect ejecicio
```

* Creando esquemas para la base ejercicio

```
create schema "$user";
create schema dirty;
create schema clean;
create schema shameful;
create schema playground;
create schema output;
create schema mining;
create schema ml;
create schema mis_extensiones;
```

* Modificando el path de búsqueda

```
alter database ejercicio set search_path="$user", dirty, clean, shameful, playground, output, mining, ml, mis_extensiones;
```

* Permisos en los esquemas

```
grant usage on schema dirty to public;

alter default privileges in schema dirty 
grant select, references on tables to public;

alter default privileges in schema dirty
grant select, update on sequences to public;

alter default privileges in schema dirty
grant execute on functions to public;

alter default privileges in schema dirty
grant usage on types to public;
```

* Creando extensiones

```
create extension dblink schema mis_extensiones;
create extension file_fdw schema mis_extensiones;
create extension fuzzystrmatch schema mis_extensiones;
create extension hstore schema mis_extensiones;
create extension pgcrypto schema mis_extensiones;
create extension postgres_fdw schema mis_extensiones;
create extension tablefunc schema mis_extensiones;
create extension auto_explain schema mis_extensiones;
create extension cube schema mis_extensiones;
create extension dict_xsyn schema mis_extensiones;
create extension pg_trgm schema mis_extensiones;
create extension "uuid-ossp" schema mis_extensiones;
```

* Creamos el lenguaje Phyton en la base

```
create language plpythonu;
```

#### Creando tabla original _transacciones_ en Postgresql

```
SELECT
  generate_series::date AS fecha,
  cus.tarjeta AS tarjeta,
  (ARRAY['ATM', 'COMERCIO', 'INTERNET'])[trunc(random() * 3) + 1] AS tipo_comercio,
  (random() * 10000 + 1)::int AS monto
INTO transacciones
FROM 
  generate_series((now() - '100 days'::interval)::date, now()::date, '1 day'::interval),
  (SELECT 
      uuid_generate_v4()::char(36) AS tarjeta
   FROM 
      generate_series(1,15)) AS cus;
```

Observamos las 20 primeras filas de la tabla

```
SELECT * FROM transacciones LIMIT 20;
```

#### Creando tabla modificada _transacciones_1_ en Potgresql

Las modificaciones que se incluyen a la tabla `transacciones` son:

* Se incluye la columna _colonia_ la cual puede tener 10 valores. Se conideran los valores: COL_1, COL_2, COL_3, COL_4, COL_5, COL_6, COL_7, COL_8, COL_9, col_10.

* Se modifica el generador de datos para incluir horas en las fechas y que las trajetas no transaccionen todos los días.

```
SELECT
  generate_series::timestamp AS fecha,
  cus.tarjeta AS tarjeta,
  (ARRAY['ATM', 'COMERCIO', 'INTERNET'])[trunc(random() * 3) + 1] AS tipo_comercio,
  (ARRAY['COL_1', 'COL_2', 'COL_3', 'COL_4', 'COL_5', 'COL_6', 'COL_7', 'COL_8', 'COL_9'  , 'col_10'])[trunc(random() * 10) + 1] AS colonia,
  (random() * 10000 + 1)::int AS monto
INTO transacciones_12
FROM 
  generate_series((now() - '100 days'::interval)::timestamp, now()::timestamp, 
  ((((trunc(random() * 7) + 2)::integer)::char || ' days')::interval)),
  (SELECT 
      uuid_generate_v4()::char(36) AS tarjeta 
   FROM 
      generate_series(1,15)) AS cus;
```

Observamos las 20 primeras filas de la tabla:

```
SELECT * FROM transacciones_1 LIMIT 20;
```